"use client";
import {useEffect,useState} from "react";
import {ArrowRight,BarChart3,BookOpen,CalendarDays,Check,ChevronRight,FileText,Globe2,Instagram,LayoutDashboard,Library,Link2,LogOut,Menu,PenTool,Play,Plus,Search,Send,Settings,Share2,Sparkles,Target,TrendingUp,Video,WandSparkles,X,Zap} from "lucide-react";

const menu=[["Dashboard",LayoutDashboard],["Analisi",BarChart3],["Idee & Script",BookOpen],["Crea contenuti",Sparkles],["Calendario",CalendarDays],["Libreria",Library],["Social collegati",Share2],["Impostazioni",Settings]];
const scripts=[
 {type:"REEL",title:"3 errori che il tuo cliente sta facendo",desc:"Hook forte → errori → soluzione → CTA",tag:"Educativo"},
 {type:"CAROSELLO",title:"La checklist definitiva",desc:"Problema → 5 punti pratici → salvataggio",tag:"Valore"},
 {type:"REEL",title:"Prima pensavo... oggi invece...",desc:"Storytelling → svolta → insegnamento",tag:"Storytelling"},
 {type:"POST",title:"Mito vs realtà",desc:"Credenza comune → verità → spiegazione",tag:"Autorità"},
 {type:"STORIES",title:"Sondaggio che genera conversazioni",desc:"Domanda → opzioni → follow-up → CTA",tag:"Engagement"},
 {type:"REEL",title:"Se fai questo, fermati",desc:"Pattern interrupt → problema → consiglio",tag:"Hook"}
];

export default function Home(){
 const [mode,setMode]=useState("welcome"),[active,setActive]=useState("Dashboard"),[mobile,setMobile]=useState(false),[url,setUrl]=useState(""),[business,setBusiness]=useState(""),[analysis,setAnalysis]=useState(false);
 useEffect(()=>{try{if(localStorage.getItem("rps_session"))setMode("app")}catch(e){}},[]);
 const enter=()=>{try{localStorage.setItem("rps_session","demo")}catch(e){}setMode("app")};
 const logout=()=>{try{localStorage.removeItem("rps_session")}catch(e){}setMode("welcome")};
 if(mode==="welcome")return <Landing enter={enter}/>;
 return <main className="app"><Sidebar active={active} setActive={setActive} mobile={mobile} setMobile={setMobile} logout={logout}/><section className="main"><Topbar setMobile={setMobile}/><div className="page">{active==="Dashboard"&&<Dashboard setActive={setActive}/>} {active==="Analisi"&&<Analysis url={url} setUrl={setUrl} business={business} setBusiness={setBusiness} analysis={analysis} setAnalysis={setAnalysis} setActive={setActive}/>} {active==="Idee & Script"&&<Scripts/>} {active==="Crea contenuti"&&<Creator/>} {active==="Calendario"&&<Calendar/>} {active==="Libreria"&&<Empty icon={Library} title="La tua libreria" text="Qui troverai bozze, script e contenuti salvati."/>} {active==="Social collegati"&&<Empty icon={Share2} title="Collega i tuoi social" text="Instagram, Facebook, LinkedIn e TikTok saranno gestiti da qui."/>} {active==="Impostazioni"&&<Empty icon={Settings} title="Impostazioni RP Social" text="Profilo attività, Brand Voice, account e abbonamento."/>}</div></section></main>;
}

function Brand(){return <div className="brand"><div className="rpmark"><b>R</b><b>P</b></div><div><strong>RP <em>SOCIAL</em></strong><small>BY RP DIGITAL</small></div></div>}
function Landing({enter}){return <main className="landing"><div className="redglow g1"/><div className="redglow g2"/><nav className="landingnav"><Brand/><div className="navlinks"><span>Funzionalità</span><span>Come funziona</span><span>Prezzi</span><span>FAQ</span></div><div className="navactions"><button className="outline" onClick={enter}>Accedi</button><button className="redbtn" onClick={enter}>Registrati</button></div></nav><section className="hero"><div className="herocopy"><div className="kicker">— IL TUO <b>SOCIAL MEDIA MANAGER DIGITALE</b></div><h1>Analizza. Crea.<br/>Organizza. <em>Pubblica.</em></h1><p>Inserisci il tuo sito web o i link dei tuoi social. RP Social analizza la tua presenza online, ti suggerisce cosa migliorare e trasforma la strategia in contenuti pronti.</p><div className="heroactions"><button className="redbtn big" onClick={enter}><Zap/> Inizia gratis <ArrowRight/></button><button className="outline big" onClick={enter}><Play/> Guarda la demo</button></div><div className="ticks"><span><Check/> Analisi automatica</span><span><Check/> Script con AI</span><span><Check/> Calendario editoriale</span></div></div><HeroDashboard/></section><section className="features">{[[Search,"Analisi automatica","Scopri cosa migliorare partendo dal tuo sito o dai social."],[BookOpen,"Idee e script pronti","Un database di strutture già pensate per creare contenuti."],[Sparkles,"Contenuti con AI","Post, Reel, caroselli e Stories personalizzati sul tuo brand."],[CalendarDays,"Calendario editoriale","Organizza e prepara la programmazione dei contenuti."],[TrendingUp,"Più risultati","Una strategia semplice per migliorare la presenza online."]].map(([I,t,d])=><div className="feature" key={t}><I/><b>{t}</b><p>{d}</p></div>)}</section><section className="steps"><div className="kicker">— COME FUNZIONA</div><h2>Dalla tua attività ai contenuti pronti in <em>4 step</em></h2><div className="stepgrid">{[[Link2,"Inserisci sito o social","Partiamo dalla tua presenza online."],[BarChart3,"Ricevi l'analisi","Punti di forza, criticità e piano d'azione."],[FileText,"Ottieni idee e script","Contenuti personalizzati per la tua attività."],[Send,"Crea, organizza e pubblica","Dal contenuto al calendario in pochi clic."]].map(([I,t,d],i)=><div className="step" key={t}><span>{i+1}</span><I/><div><b>{t}</b><p>{d}</p></div></div>)}</div></section><Footer/></main>}
function HeroDashboard(){return <div className="heroapp"><div className="appbar"><i/><i/><i/><small>RP SOCIAL</small></div><div className="heroin"><aside><b>RP</b>{[1,2,3,4,5,6].map(x=><i key={x}/>)}</aside><div className="dashmock"><small>DASHBOARD</small><h3>Ciao 👋</h3><p>Ecco la panoramica della tua attività</p><div className="mockstats"><div><b>78<small>/100</small></b><span>Social Score</span></div><div><b>24</b><span>Contenuti creati</span></div><div><b>12</b><span>Programmati</span></div></div><div className="mocktitle">Prossimi contenuti</div><div className="mockcards">{["REEL","POST","CAROSELLO","STORY"].map((x,i)=><div key={x}><span>{x}</span><i style={{height:(45+i*13)+"%"}}/></div>)}</div></div></div><div className="float f1"><BarChart3/><b>Analisi automatica</b><span>Social Score 78/100</span></div><div className="float f2"><FileText/><b>Idee & Script AI</b><span>Pronti per la tua attività</span></div><div className="float f3"><CalendarDays/><b>Calendario editoriale</b><span>Organizza e programma</span></div></div>}
function Sidebar({active,setActive,mobile,setMobile,logout}){return <aside className={"sidebar "+(mobile?"open":"")}><div className="sidehead"><Brand/><button onClick={()=>setMobile(false)}><X/></button></div><div className="workspace"><div>RP</div><span><b>Il tuo workspace</b><small>Piano PRO</small></span></div><nav>{menu.map(([n,I])=><button className={active===n?"active":""} onClick={()=>{setActive(n);setMobile(false)}} key={n}><I/>{n}</button>)}</nav><div className="sidebottom"><div className="upgrade"><Sparkles/><b>RP Social AI</b><p>Strategia e contenuti in un unico spazio.</p></div><button className="logout" onClick={logout}><LogOut/> Esci</button></div></aside>}
function Topbar({setMobile}){return <header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="topsearch"><Search/><span>Cerca in RP Social...</span></div><div className="topright"><span className="plan">PRO</span><div className="avatar">RP</div></div></header>}
function Dashboard({setActive}){return <><div className="pagehead"><div><span className="eyebrow">RP SOCIAL DASHBOARD</span><h1>Cosa pubblichiamo oggi?</h1><p>Strategia, idee e contenuti pronti per la tua attività.</p></div><button className="redbtn" onClick={()=>setActive("Crea contenuti")}><Plus/> Crea contenuto</button></div><div className="scoregrid"><div className="scorecard"><div className="score"><b>78</b><span>/100</span></div><div><small>SOCIAL SCORE</small><h3>Buona base. Possiamo fare meglio.</h3><p>Completa l'analisi per ricevere un piano personalizzato.</p><button onClick={()=>setActive("Analisi")}>Vedi analisi <ChevronRight/></button></div></div>{[[FileText,"24","Contenuti creati","+6 questa settimana"],[CalendarDays,"12","Programmati","Prossimi 7 giorni"],[TrendingUp,"+28%","Potenziale crescita","Con più costanza"]].map(([I,v,t,s])=><div className="metric" key={t}><I/><b>{v}</b><span>{t}</span><small>{s}</small></div>)}</div><div className="twocol"><section className="panel today"><div className="panelhead"><div><small>CONSIGLIO DEL GIORNO</small><h2>Oggi crea un Reel educativo</h2></div><span className="redpill">CONSIGLIATO</span></div><div className="idea"><div className="reelicon"><Video/></div><div><b>3 errori che i tuoi clienti fanno prima di scegliere...</b><p>Un contenuto rapido che aumenta autorevolezza e salvataggi.</p><div className="tags"><span>Reel</span><span>Educativo</span><span>30-45 sec</span></div></div></div><button className="redbtn" onClick={()=>setActive("Crea contenuti")}><WandSparkles/> Crea questo contenuto</button></section><section className="panel quickpanel"><small>ACCESSO RAPIDO</small><h2>Da dove vuoi partire?</h2>{[[BarChart3,"Analizza la mia presenza","Scopri cosa migliorare","Analisi"],[BookOpen,"Trova uno script","Idee già strutturate","Idee & Script"],[CalendarDays,"Pianifica la settimana","Organizza i contenuti","Calendario"]].map(([I,t,d,a])=><button onClick={()=>setActive(a)} key={t}><I/><span><b>{t}</b><small>{d}</small></span><ChevronRight/></button>)}</section></div></>}
function Analysis({url,setUrl,business,setBusiness,analysis,setAnalysis,setActive}){return <><div className="pagehead"><div><span className="eyebrow">ANALISI AUTOMATICA</span><h1>Partiamo dalla tua presenza online.</h1><p>Inserisci sito web o profilo social e costruiamo la tua strategia.</p></div></div>{!analysis?<section className="analysisbox panel"><div className="analysisicon"><Search/></div><h2>Analizza la mia attività</h2><p>RP Social userà queste informazioni per preparare il profilo del brand e il piano contenuti.</p><label>Nome attività<input value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Es. RP Digital"/></label><label>Sito web o link social<div className="urlinput"><Globe2/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></div></label><button className="redbtn big" onClick={()=>setAnalysis(true)}><Sparkles/> Avvia pre-analisi</button><small className="demowarn">V8 demo: l'analisi mostrata è dimostrativa. Il motore AI reale verrà collegato nel backend.</small></section>:<AnalysisResult setActive={setActive}/>}</>}
function AnalysisResult({setActive}){return <><div className="analysisresult"><section className="panel scorebig"><div className="ring"><b>72</b><span>/100</span></div><div><small>SOCIAL SCORE</small><h2>Buon potenziale, ma manca una struttura.</h2><p>La presenza online è avviata. Possiamo migliorare costanza, varietà e conversione.</p></div></section><section className="panel findings"><h2>Pre-analisi</h2>{[[Check,"Profilo","Identità chiara, CTA da rafforzare"],[FileText,"Contenuti","Serve maggiore continuità editoriale"],[Video,"Formati","Aumentare Reel e contenuti educativi"],[Target,"Strategia","Creare rubriche riconoscibili e ricorrenti"]].map(([I,t,d])=><div key={t}><I/><span><b>{t}</b><small>{d}</small></span></div>)}</section></div><section className="panel actionplan"><div><small>PIANO D'AZIONE CONSIGLIATO</small><h2>La tua prossima settimana</h2></div><div className="planitems"><span><b>01</b> 1 Reel educativo</span><span><b>02</b> 1 Carosello di valore</span><span><b>03</b> 1 Post autorevolezza</span><span><b>04</b> Stories di engagement</span></div><button className="redbtn" onClick={()=>setActive("Idee & Script")}>Crea il mio piano editoriale <ArrowRight/></button></section></>}
function Scripts(){return <><div className="pagehead"><div><span className="eyebrow">SCRIPT LIBRARY</span><h1>Non partire mai da una pagina bianca.</h1><p>Scegli una struttura e adattala alla tua attività.</p></div></div><div className="filters"><button className="active">Tutti</button><button>Reel</button><button>Post</button><button>Caroselli</button><button>Stories</button></div><div className="scriptgrid">{scripts.map(s=><article className="scriptcard" key={s.title}><div><span>{s.type}</span><em>{s.tag}</em></div><FileText/><h3>{s.title}</h3><p>{s.desc}</p><button>Personalizza per la mia attività <WandSparkles/></button></article>)}</div></>}
function Creator(){const [type,setType]=useState("Reel"),[topic,setTopic]=useState("");return <><div className="pagehead"><div><span className="eyebrow">CONTENT STUDIO</span><h1>Trasforma un'idea in contenuto.</h1><p>RP Social prepara struttura, testo, CTA e indicazioni creative.</p></div></div><div className="creatorgrid"><section className="panel createform"><label>Formato<div className="formatrow">{["Post","Reel","Carosello","Stories"].map(x=><button className={type===x?"active":""} onClick={()=>setType(x)} key={x}>{x}</button>)}</div></label><label>Di cosa vuoi parlare?<textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Es. 3 errori da evitare quando..."/></label><label>Obiettivo<select><option>Educare</option><option>Vendere</option><option>Creare engagement</option><option>Aumentare autorevolezza</option></select></label><button className="redbtn big"><Sparkles/> Genera con RP Social AI</button></section><section className="panel result"><span className="redpill">ANTEPRIMA</span><h2>{topic||"Il tuo contenuto apparirà qui"}</h2><p><b>HOOK</b><br/>Se stai facendo questo, probabilmente stai perdendo un'opportunità importante.</p><p><b>SVILUPPO</b><br/>Spiega il problema in modo semplice, mostra la soluzione e aggiungi un esempio concreto.</p><p><b>CTA</b><br/>Salva questo contenuto e seguici per altri consigli.</p><div className="resultactions"><button>Modifica</button><button>Salva in libreria</button></div></section></div></>}
function Calendar(){return <><div className="pagehead"><div><span className="eyebrow">CALENDARIO EDITORIALE</span><h1>La settimana sotto controllo.</h1><p>Organizza contenuti e preparali per la programmazione.</p></div><button className="redbtn"><Plus/> Nuovo contenuto</button></div><div className="week">{["LUN 12","MAR 13","MER 14","GIO 15","VEN 16"].map((d,i)=><div className="day" key={d}><b>{d}</b>{i<4&&<article><span>{["REEL","POST","CAROSELLO","STORY"][i]}</span><p>{["3 errori da evitare","Caso cliente","5 consigli pratici","Dietro le quinte"][i]}</p><small>{10+i}:00</small></article>}<button><Plus/></button></div>)}</div></>}
function Empty({icon:Icon,title,text}){return <section className="empty panel"><div><Icon/></div><span className="eyebrow">RP SOCIAL</span><h1>{title}</h1><p>{text}</p><button className="redbtn">Sezione predisposta</button></section>}
function Footer(){return <footer>© 2026 RP Social — un prodotto RP Digital — P. IVA 01242270575 <span>Privacy · Cookie · Termini</span></footer>}
